{ username, fullUsername, config, pkgs, ... }: {
  users.groups = {
    "${username}" = {};
  };

  users.mutableUsers = false;

  users.users."${username}" = {
    description = fullUsername;
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    initialHashedPassword = "$7$CU..../....aOiNxb.jKF62FFvhuMLBR.$EOVnTizw5wRSqD3MiMZ6rm04.V/FNNjvTC7fr4soPo2";
    home = "/home/${username}";
    isNormalUser = true;
    extraGroups = [
      username
      "users"
      "wheel"
      "libvirtd"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJoALbDUzGjj4w8zl7c9jVOWWDagjTkNtqrhJLpRJSz8 froup@sonata"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFog+xBaFU3tQCFOY6219+DDhOna+zITforRndZtdOcJ froup@symphony"
    ];
  };
  users.users.root = {
    initialHashedPassword = config.users.users."${username}".initialHashedPassword;
    openssh.authorizedKeys.keys = config.users.users."${username}".openssh.authorizedKeys.keys;
  };

  # ssh-agent is used to pull my private secrets repo from github when deploying my nixos config.
  programs.ssh.startAgent = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    neovim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    git
    gnumake
    wget
    curl
  ];

  system.stateVersion = "23.11";
}
