# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot";

  boot.loader.systemd-boot.enable = true;

  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8a7b8247-babe-454d-a5d6-a43c51e6cd66";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:1" "noatime" ];
    };

  boot.initrd.luks.devices."crypted-nixos".device = "/dev/disk/by-uuid/f5883437-1c6c-4b9b-9ba7-e9886f3f387a";
  boot.initrd.luks.devices."crypted-nixos".allowDiscards = true;
  boot.initrd.luks.devices."crypted-nixos".bypassWorkqueues = true;

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "relatime" "mode=755" "size=8G" "defaults" ];
  };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/8a7b8247-babe-454d-a5d6-a43c51e6cd66";
      fsType = "btrfs";
      options = [ "subvol=@persistent" "compress-force=zstd:1" ];
      neededForBoot = true;
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/8a7b8247-babe-454d-a5d6-a43c51e6cd66";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress-force=zstd:1" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/8a7b8247-babe-454d-a5d6-a43c51e6cd66";
      fsType = "btrfs";
      options = [ "subvol=@swap" "ro" ];
    };

  fileSystems."/swap/swapfile" = {
    depends = [ "/swap" ];
    device = "/swap/swapfile";
    fsType = "none";
    options = [ "bind" "rw" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BCCB-AA4B";
      fsType = "vfat";
      options = [ "umask=0077" "defaults" ];
    };

  swapDevices = [
    {
      device = "/swap/swapfile";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens33.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
